"""Emit a single self-contained script that validates dfa_torch against the real CUDA kernel.

`dfa_torch.py` is currently validated only against my own transcription of
`deformable_aggregation_cuda.cu`. That catches misreadings of the kernel but cannot catch
a misreading shared by both. The authoritative check needs an actual GPU.

Rather than provisioning one, this bundles everything into one file you can paste into a
free Colab or Kaggle notebook: the CUDA sources, the pure-PyTorch implementation, and the
comparison. No repo checkout, no pip install, no mmdet3d.

Two portability fixes are applied while bundling:
  * `#include <THC/THCAtomics.cuh>` -> `<ATen/cuda/Atomic.cuh>`. THC was removed in
    PyTorch 1.11; upstream's source predates that and will not compile on a modern
    Colab/Kaggle image.
  * the extension is built with `torch.utils.cpp_extension.load` (JIT) instead of
    `setup.py`, so nothing has to be installed into site-packages.

Usage:
    python diffusiondrive_planner/tools/make_cuda_validation_bundle.py
    # -> diffusiondrive_planner/tools/validate_dfa_cuda.py   (upload this one file)
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OPS = ROOT / "upstream-nusc" / "projects" / "mmdet3d_plugin" / "ops" / "src"
OUT = Path(__file__).resolve().parent / "validate_dfa_cuda.py"

HEADER = '''"""Validate the pure-PyTorch Deformable Aggregation against the real CUDA kernel.

SELF-CONTAINED — paste into a free Colab/Kaggle GPU notebook and run. No pip install,
no repo checkout. Needs only torch with CUDA and a working nvcc (both preinstalled on
Colab and Kaggle GPU runtimes).

    Colab:  Runtime -> Change runtime type -> T4 GPU
    Kaggle: Settings -> Accelerator -> GPU T4 x2

AUTO-GENERATED by make_cuda_validation_bundle.py — edit that, not this.
"""

import os
import tempfile

import torch
import torch.nn.functional as F

assert torch.cuda.is_available(), "no CUDA device — enable the GPU runtime"
print("torch", torch.__version__, "| device:", torch.cuda.get_device_name(0))

'''

FOOTER = '''

# --------------------------------------------------------------- build the kernel

def build_extension():
    from torch.utils.cpp_extension import load

    tmp = tempfile.mkdtemp(prefix="dfa_")
    (open(os.path.join(tmp, "deformable_aggregation.cpp"), "w")
     .write(CPP_SOURCE))
    (open(os.path.join(tmp, "deformable_aggregation_cuda.cu"), "w")
     .write(CU_SOURCE))

    print("compiling deformable_aggregation_ext (about a minute)...")
    return load(
        name="deformable_aggregation_ext",
        sources=[
            os.path.join(tmp, "deformable_aggregation.cpp"),
            os.path.join(tmp, "deformable_aggregation_cuda.cu"),
        ],
        extra_cuda_cflags=["-O3"],
        verbose=False,
    )


# ------------------------------------------------------------------- test inputs

SHAPES = [[(6, 8), (3, 4), (2, 2)], [(5, 7), (3, 3), (2, 3)]]  # per cam, per level
B, A, P, C, G = 2, 3, 4, 8, 2


def build_inputs(seed, dtype=torch.float32, big=False):
    """Random inputs, with border/outside sampling locations mixed in."""
    if big:
        shapes = [[(32, 88), (16, 44), (8, 22), (4, 11)] for _ in range(6)]
        b, a, p, c, g = 1, 900, 13, 256, 8
    else:
        shapes, b, a, p, c, g = SHAPES, B, A, P, C, G

    gen = torch.Generator().manual_seed(seed)
    sizes = [h * w for cam in shapes for (h, w) in cam]
    feat = torch.randn(b, sum(sizes), c, generator=gen, dtype=dtype)
    spatial_shape = torch.tensor(shapes, dtype=torch.int64)
    starts = (torch.tensor(sizes, dtype=torch.int64).cumsum(0)
              - torch.tensor(sizes, dtype=torch.int64))
    scale_start_index = starts.reshape(len(shapes), -1)

    loc = torch.rand(b, a, p, len(shapes), 2, generator=gen, dtype=dtype)
    if not big:
        # Exercise the kernel's strict early-return.
        loc[0, 0, 0, 0] = torch.tensor([0.0, 0.5], dtype=dtype)
        loc[0, 0, 1, 0] = torch.tensor([1.0, 0.5], dtype=dtype)
        loc[0, 1, 0, 0] = torch.tensor([-0.3, 0.5], dtype=dtype)
        loc[0, 1, 1, 0] = torch.tensor([0.5, 1.7], dtype=dtype)

    weights = torch.randn(b, a, p, len(shapes), len(shapes[0]), g,
                          generator=gen, dtype=dtype)
    return [x.cuda() for x in
            (feat, spatial_shape, scale_start_index, loc, weights)]


# ------------------------------------------------------------------ diagnostics

def diagnose(name, got, want, err, denom):
    """Explain any large RELATIVE error.

    A big relative error with a tiny absolute error is the expected signature of
    float32 accumulation-order differences: the CUDA kernel sums via atomicAdd in
    nondeterministic order across cam x scale x pts, while the torch version sums in a
    fixed loop order. That shows up as a large ratio only where the true value is near
    zero, which is harmless.

    The failure mode it must be distinguished from is a genuine structural mismatch,
    which would produce large relative error on LARGE values too. So report the relative
    error restricted to elements that actually carry magnitude.
    """
    rel = err / denom
    i = int(rel.argmax())
    flat_want, flat_err = want.flatten(), err.flatten()

    scale = float(want.abs().median())
    big = want.abs() > max(scale, 1e-3)          # elements that carry real magnitude
    rel_big = float((rel[big]).max()) if bool(big.any()) else float("nan")
    frac_bad = float((rel > 1e-2).float().mean())

    print(f"{'':<28}worst-rel elem: |want|={abs(float(flat_want[i])):.3e} "
          f"err={float(flat_err[i]):.3e}")
    print(f"{'':<28}median |want|={scale:.3e} | max rel on |want|>median: {rel_big:.3e} "
          f"| frac rel>1%: {frac_bad:.2%}")
    if rel_big > 1e-3:
        print(f"{'':<28}^^ WARNING: large relative error on LARGE values — "
              f"this is NOT just accumulation order.")


# ------------------------------------------------------------------------ main

def main():
    ext = build_extension()

    print()
    print("=" * 66)
    print(f"{'case':<28}{'max abs diff':>16}{'max rel diff':>14}  verdict")
    print("=" * 66)

    worst = 0.0
    failures = 0
    cases = [("tiny seed=0", 0, False), ("tiny seed=1", 1, False),
             ("tiny seed=2", 2, False), ("realistic 900x13x256", 0, True)]

    for name, seed, big in cases:
        args = build_inputs(seed, big=big)
        feat, spatial_shape, scale_start_index, loc, weights = args

        want = ext.deformable_aggregation_forward(
            feat.contiguous().float(),
            spatial_shape.contiguous().int(),
            scale_start_index.contiguous().int(),
            loc.contiguous().float(),
            weights.contiguous().float(),
        )
        got = deformable_aggregation_torch(*args)

        denom = want.abs().clamp(min=1e-6)
        err = (got - want).abs()
        abs_d = float(err.max())
        rel_d = float((err / denom).max())
        ok = abs_d < 1e-3
        failures += (not ok)
        worst = max(worst, abs_d)
        print(f"{name:<28}{abs_d:>16.3e}{rel_d:>14.3e}  {'PASS' if ok else 'FAIL'}")
        diagnose(name, got, want, err, denom)

    print("=" * 66)
    if failures:
        print(f"\\n{failures} case(s) FAILED — dfa_torch.py does NOT match the kernel.")
        print("Do not trust any metric produced with the pure-PyTorch fallback.")
    else:
        print(f"\\nAll cases PASS (worst abs diff {worst:.3e}).")
        print("dfa_torch.py is confirmed equivalent to the CUDA kernel.")
    return failures


def _in_notebook() -> bool:
    try:
        get_ipython()  # noqa: F821  — only defined inside IPython/Jupyter
        return True
    except NameError:
        return False


# Works both as `python validate_dfa_cuda.py` and as a pasted notebook cell.
# SystemExit inside a Jupyter cell renders as an ugly traceback, so it is only
# raised when actually running as a script.
_rc = main()
if _rc and not _in_notebook():
    raise SystemExit(_rc)
'''


def read_source(name: str) -> str:
    text = (OPS / name).read_text()
    # THC was removed in PyTorch 1.11; modern Colab/Kaggle images will not compile it.
    return text.replace(
        "#include <THC/THCAtomics.cuh>", "#include <ATen/cuda/Atomic.cuh>"
    )


def extract_torch_impl() -> str:
    """Take deformable_aggregation_torch from dfa_torch.py, minus its module header."""
    text = (ROOT / "dfa_torch.py").read_text()
    marker = "def deformable_aggregation_torch("
    idx = text.index(marker)
    end = text.index("class _DeformableAggregationTorchShim")
    return text[idx:end].rstrip() + "\n"


def main() -> None:
    cpp = read_source("deformable_aggregation.cpp")
    cu = read_source("deformable_aggregation_cuda.cu")

    parts = [
        HEADER,
        "CPP_SOURCE = r'''\n" + cpp + "\n'''\n\n",
        "CU_SOURCE = r'''\n" + cu + "\n'''\n\n",
        "# ---------------------- pure-PyTorch implementation under test ----------------\n",
        "# Copied verbatim from diffusiondrive_planner/dfa_torch.py\n\n",
        extract_torch_impl(),
        FOOTER,
    ]
    OUT.write_text("".join(parts))
    print(f"wrote {OUT}  ({OUT.stat().st_size / 1024:.0f} KB)")
    print("Upload that single file to a Colab/Kaggle GPU notebook and run it.")


if __name__ == "__main__":
    main()
