"""Validate the pure-PyTorch Deformable Aggregation against the real CUDA kernel.

SELF-CONTAINED — paste into a free Colab/Kaggle GPU notebook and run. No pip install,
no repo checkout. Needs only torch with CUDA and a working nvcc (both preinstalled on
Colab and Kaggle GPU runtimes).

    Colab:  Runtime -> Change runtime type -> T4 GPU
    Kaggle: Settings -> Accelerator -> GPU T4 x2

AUTO-GENERATED by make_cuda_validation_bundle.py — edit that, not this.
"""

import os
import tempfile

import torch
import torch.nn.functional as F

assert torch.cuda.is_available(), "no CUDA device — enable the GPU runtime"
print("torch", torch.__version__, "| device:", torch.cuda.get_device_name(0))

CPP_SOURCE = r'''
#include <torch/extension.h>
#include <c10/cuda/CUDAGuard.h>

void deformable_aggregation(
  float* output,
  const float* mc_ms_feat,
  const int* spatial_shape,
  const int* scale_start_index,
  const float* sample_location,
  const float* weights,
  int batch_size,
  int num_cams,
  int num_feat,
  int num_embeds,
  int num_scale,
  int num_anchors,
  int num_pts,
  int num_groups
);
  

/* feat: bs, num_feat, c */
/* _spatial_shape: cam, scale, 2 */
/* _scale_start_index: cam, scale */
/* _sampling_location: bs, anchor, pts, cam, 2 */
/* _weights: bs, anchor, pts, cam, scale, group */
/* output: bs, anchor, c */
/* kernel: bs, anchor, pts, c */


at::Tensor deformable_aggregation_forward(
  const at::Tensor &_mc_ms_feat,
  const at::Tensor &_spatial_shape,
  const at::Tensor &_scale_start_index,
  const at::Tensor &_sampling_location,
  const at::Tensor &_weights
) {
  at::DeviceGuard guard(_mc_ms_feat.device());
  const at::cuda::OptionalCUDAGuard device_guard(device_of(_mc_ms_feat));
  int batch_size = _mc_ms_feat.size(0);
  int num_feat = _mc_ms_feat.size(1);
  int num_embeds = _mc_ms_feat.size(2);
  int num_cams = _spatial_shape.size(0);
  int num_scale = _spatial_shape.size(1);
  int num_anchors = _sampling_location.size(1);
  int num_pts = _sampling_location.size(2);
  int num_groups = _weights.size(5);

  const float* mc_ms_feat = _mc_ms_feat.data_ptr<float>();
  const int* spatial_shape = _spatial_shape.data_ptr<int>();
  const int* scale_start_index = _scale_start_index.data_ptr<int>();
  const float* sampling_location = _sampling_location.data_ptr<float>();
  const float* weights = _weights.data_ptr<float>();

  auto output = at::zeros({batch_size, num_anchors, num_embeds}, _mc_ms_feat.options());
  deformable_aggregation(
    output.data_ptr<float>(),
    mc_ms_feat, spatial_shape, scale_start_index, sampling_location, weights,
    batch_size, num_cams, num_feat, num_embeds, num_scale, num_anchors, num_pts, num_groups
  );
  return output;
}


void deformable_aggregation_grad(
  const float* mc_ms_feat,
  const int* spatial_shape,
  const int* scale_start_index,
  const float* sample_location,
  const float* weights,
  const float* grad_output,
  float* grad_mc_ms_feat,
  float* grad_sampling_location,
  float* grad_weights,
  int batch_size,
  int num_cams,
  int num_feat,
  int num_embeds,
  int num_scale,
  int num_anchors,
  int num_pts,
  int num_groups
);


void deformable_aggregation_backward(
  const at::Tensor &_mc_ms_feat,
  const at::Tensor &_spatial_shape,
  const at::Tensor &_scale_start_index,
  const at::Tensor &_sampling_location,
  const at::Tensor &_weights,
  const at::Tensor &_grad_output,
  at::Tensor &_grad_mc_ms_feat,
  at::Tensor &_grad_sampling_location,
  at::Tensor &_grad_weights
) {
  at::DeviceGuard guard(_mc_ms_feat.device());
  const at::cuda::OptionalCUDAGuard device_guard(device_of(_mc_ms_feat));
  int batch_size = _mc_ms_feat.size(0);
  int num_feat = _mc_ms_feat.size(1);
  int num_embeds = _mc_ms_feat.size(2);
  int num_cams = _spatial_shape.size(0);
  int num_scale = _spatial_shape.size(1);
  int num_anchors = _sampling_location.size(1);
  int num_pts = _sampling_location.size(2);
  int num_groups = _weights.size(5);

  const float* mc_ms_feat = _mc_ms_feat.data_ptr<float>();
  const int* spatial_shape = _spatial_shape.data_ptr<int>();
  const int* scale_start_index = _scale_start_index.data_ptr<int>();
  const float* sampling_location = _sampling_location.data_ptr<float>();
  const float* weights = _weights.data_ptr<float>();
  const float* grad_output = _grad_output.data_ptr<float>();

  float* grad_mc_ms_feat = _grad_mc_ms_feat.data_ptr<float>();
  float* grad_sampling_location = _grad_sampling_location.data_ptr<float>();
  float* grad_weights = _grad_weights.data_ptr<float>();

  deformable_aggregation_grad(
    mc_ms_feat, spatial_shape, scale_start_index, sampling_location, weights,
    grad_output, grad_mc_ms_feat, grad_sampling_location, grad_weights,
    batch_size, num_cams, num_feat, num_embeds, num_scale, num_anchors, num_pts, num_groups
  );
}


PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
  m.def(
    "deformable_aggregation_forward",
    &deformable_aggregation_forward,
    "deformable_aggregation_forward"
  );
  m.def(
    "deformable_aggregation_backward",
    &deformable_aggregation_backward,
    "deformable_aggregation_backward"
  );
}

'''

CU_SOURCE = r'''

#include <ATen/ATen.h>
#include <ATen/cuda/CUDAContext.h>
#include <cuda.h>
#include <cuda_runtime.h>

#include <ATen/cuda/Atomic.cuh>

#include <iostream>
#include <stdlib.h>


__device__ float bilinear_sampling(
    const float *&bottom_data, const int &height, const int &width,
    const int &num_embeds, const float &h_im, const float &w_im,
    const int &base_ptr
) {
  const int h_low = floorf(h_im);
  const int w_low = floorf(w_im);
  const int h_high = h_low + 1;
  const int w_high = w_low + 1;

  const float lh = h_im - h_low;
  const float lw = w_im - w_low;
  const float hh = 1 - lh, hw = 1 - lw;

  const int w_stride = num_embeds;
  const int h_stride = width * w_stride;
  const int h_low_ptr_offset = h_low * h_stride;
  const int h_high_ptr_offset = h_low_ptr_offset + h_stride;
  const int w_low_ptr_offset = w_low * w_stride;
  const int w_high_ptr_offset = w_low_ptr_offset + w_stride;

  float v1 = 0;
  if (h_low >= 0 && w_low >= 0) {
    const int ptr1 = h_low_ptr_offset + w_low_ptr_offset + base_ptr;
    v1 = bottom_data[ptr1];
  }
  float v2 = 0;
  if (h_low >= 0 && w_high <= width - 1) {
    const int ptr2 = h_low_ptr_offset + w_high_ptr_offset + base_ptr;
    v2 = bottom_data[ptr2];
  }
  float v3 = 0;
  if (h_high <= height - 1 && w_low >= 0) {
    const int ptr3 = h_high_ptr_offset + w_low_ptr_offset + base_ptr;
    v3 = bottom_data[ptr3];
  }
  float v4 = 0;
  if (h_high <= height - 1 && w_high <= width - 1) {
    const int ptr4 = h_high_ptr_offset + w_high_ptr_offset + base_ptr;
    v4 = bottom_data[ptr4];
  }

  const float w1 = hh * hw, w2 = hh * lw, w3 = lh * hw, w4 = lh * lw;

  const float val = (w1 * v1 + w2 * v2 + w3 * v3 + w4 * v4);
  return val;
}


__device__ void bilinear_sampling_grad(
    const float *&bottom_data, const float &weight,
    const int &height, const int &width,
    const int &num_embeds, const float &h_im, const float &w_im,
    const int &base_ptr,
    const float &grad_output,
    float *&grad_mc_ms_feat, float *grad_sampling_location, float *grad_weights) {
  const int h_low = floorf(h_im);
  const int w_low = floorf(w_im);
  const int h_high = h_low + 1;
  const int w_high = w_low + 1;

  const float lh = h_im - h_low;
  const float lw = w_im - w_low;
  const float hh = 1 - lh, hw = 1 - lw;

  const int w_stride = num_embeds;
  const int h_stride = width * w_stride;
  const int h_low_ptr_offset = h_low * h_stride;
  const int h_high_ptr_offset = h_low_ptr_offset + h_stride;
  const int w_low_ptr_offset = w_low * w_stride;
  const int w_high_ptr_offset = w_low_ptr_offset + w_stride;

  const float w1 = hh * hw, w2 = hh * lw, w3 = lh * hw, w4 = lh * lw;
  const float top_grad_mc_ms_feat = grad_output * weight;
  float grad_h_weight = 0, grad_w_weight = 0;

  float v1 = 0;
  if (h_low >= 0 && w_low >= 0) {
    const int ptr1 = h_low_ptr_offset + w_low_ptr_offset + base_ptr;
    v1 = bottom_data[ptr1];
    grad_h_weight -= hw * v1;
    grad_w_weight -= hh * v1;
    atomicAdd(grad_mc_ms_feat + ptr1, w1 * top_grad_mc_ms_feat);
  }
  float v2 = 0;
  if (h_low >= 0 && w_high <= width - 1) {
    const int ptr2 = h_low_ptr_offset + w_high_ptr_offset + base_ptr;
    v2 = bottom_data[ptr2];
    grad_h_weight -= lw * v2;
    grad_w_weight += hh * v2;
    atomicAdd(grad_mc_ms_feat + ptr2, w2 * top_grad_mc_ms_feat);
  }
  float v3 = 0;
  if (h_high <= height - 1 && w_low >= 0) {
    const int ptr3 = h_high_ptr_offset + w_low_ptr_offset + base_ptr;
    v3 = bottom_data[ptr3];
    grad_h_weight += hw * v3;
    grad_w_weight -= lh * v3;
    atomicAdd(grad_mc_ms_feat + ptr3, w3 * top_grad_mc_ms_feat);
  }
  float v4 = 0;
  if (h_high <= height - 1 && w_high <= width - 1) {
    const int ptr4 = h_high_ptr_offset + w_high_ptr_offset + base_ptr;
    v4 = bottom_data[ptr4];
    grad_h_weight += lw * v4;
    grad_w_weight += lh * v4;
    atomicAdd(grad_mc_ms_feat + ptr4, w4 * top_grad_mc_ms_feat);
  }

  const float val = (w1 * v1 + w2 * v2 + w3 * v3 + w4 * v4);
  atomicAdd(grad_weights, grad_output * val);
  atomicAdd(grad_sampling_location, width * grad_w_weight * top_grad_mc_ms_feat);
  atomicAdd(grad_sampling_location + 1, height * grad_h_weight * top_grad_mc_ms_feat);
}


__global__ void deformable_aggregation_kernel(
    const int num_kernels,
    float* output,
    const float* mc_ms_feat,
    const int* spatial_shape,
    const int* scale_start_index,
    const float* sample_location,
    const float* weights,
    int batch_size,
    int num_cams,
    int num_feat,
    int num_embeds,
    int num_scale,
    int num_anchors,
    int num_pts,
    int num_groups
) {
    int idx = blockIdx.x * blockDim.x + threadIdx.x;
    if (idx >= num_kernels) return;

    const float weight = *(weights + idx / (num_embeds / num_groups));
    const int channel_index = idx % num_embeds;
    idx /= num_embeds;
    const int scale_index = idx % num_scale;
    idx /= num_scale;

    const int cam_index = idx % num_cams;
    idx /= num_cams;
    const int pts_index = idx % num_pts;
    idx /= num_pts;

    int anchor_index = idx % num_anchors;
    idx /= num_anchors;
    const int batch_index = idx % batch_size;
    idx /= batch_size;

    anchor_index = batch_index * num_anchors + anchor_index;
    const int loc_offset = ((anchor_index * num_pts + pts_index) * num_cams + cam_index) << 1;

    const float loc_w = sample_location[loc_offset];
    if (loc_w <= 0 || loc_w >= 1) return;
    const float loc_h = sample_location[loc_offset + 1];
    if (loc_h <= 0 || loc_h >= 1) return;
    
    int cam_scale_index = cam_index * num_scale + scale_index;
    const int value_offset = (batch_index * num_feat + scale_start_index[cam_scale_index]) * num_embeds + channel_index;

    cam_scale_index = cam_scale_index << 1;
    const int h = spatial_shape[cam_scale_index];
    const int w = spatial_shape[cam_scale_index + 1];

    const float h_im = loc_h * h - 0.5;
    const float w_im = loc_w * w - 0.5;

    atomicAdd(
        output + anchor_index * num_embeds + channel_index,
        bilinear_sampling(mc_ms_feat, h, w, num_embeds, h_im, w_im, value_offset) * weight
    );
}


__global__ void deformable_aggregation_grad_kernel(
    const int num_kernels,
    const float* mc_ms_feat,
    const int* spatial_shape,
    const int* scale_start_index,
    const float* sample_location,
    const float* weights,
    const float* grad_output,
    float* grad_mc_ms_feat,
    float* grad_sampling_location,
    float* grad_weights,
    int batch_size,
    int num_cams,
    int num_feat,
    int num_embeds,
    int num_scale,
    int num_anchors,
    int num_pts,
    int num_groups
) {
    int idx = blockIdx.x * blockDim.x + threadIdx.x;
    if (idx >= num_kernels) return;

    const int weights_ptr = idx / (num_embeds / num_groups);
    const int channel_index = idx % num_embeds;
    idx /= num_embeds;
    const int scale_index = idx % num_scale;
    idx /= num_scale;

    const int cam_index = idx % num_cams;
    idx /= num_cams;
    const int pts_index = idx % num_pts;
    idx /= num_pts;

    int anchor_index = idx % num_anchors;
    idx /= num_anchors;
    const int batch_index = idx % batch_size;
    idx /= batch_size;

    anchor_index = batch_index * num_anchors + anchor_index;
    const int loc_offset = ((anchor_index * num_pts + pts_index) * num_cams + cam_index) << 1;

    const float loc_w = sample_location[loc_offset];
    if (loc_w <= 0 || loc_w >= 1) return;
    const float loc_h = sample_location[loc_offset + 1];
    if (loc_h <= 0 || loc_h >= 1) return;
    
    const float grad = grad_output[anchor_index*num_embeds + channel_index];

    int cam_scale_index = cam_index * num_scale + scale_index;
    const int value_offset = (batch_index * num_feat + scale_start_index[cam_scale_index]) * num_embeds + channel_index;

    cam_scale_index = cam_scale_index << 1;
    const int h = spatial_shape[cam_scale_index];
    const int w = spatial_shape[cam_scale_index + 1];

    const float h_im = loc_h * h - 0.5;
    const float w_im = loc_w * w - 0.5;

    /* atomicAdd( */
    /*     output + anchor_index * num_embeds + channel_index, */
    /*     bilinear_sampling(mc_ms_feat, h, w, num_embeds, h_im, w_im, value_offset) * weight */
    /* ); */
    const float weight = weights[weights_ptr];
    float *grad_weights_ptr = grad_weights + weights_ptr;
    float *grad_location_ptr = grad_sampling_location + loc_offset;
    bilinear_sampling_grad(
        mc_ms_feat, weight, h, w, num_embeds, h_im, w_im,
        value_offset,
        grad,
        grad_mc_ms_feat, grad_location_ptr, grad_weights_ptr
    );
}


void deformable_aggregation(
    float* output,
    const float* mc_ms_feat,
    const int* spatial_shape,
    const int* scale_start_index,
    const float* sample_location,
    const float* weights,
    int batch_size,
    int num_cams,
    int num_feat,
    int num_embeds,
    int num_scale,
    int num_anchors,
    int num_pts,
    int num_groups
) {
    const int num_kernels = batch_size * num_pts * num_embeds * num_anchors * num_cams * num_scale;
    deformable_aggregation_kernel
        <<<(int)ceil(((double)num_kernels/128)), 128>>>(
        num_kernels, output,
        mc_ms_feat, spatial_shape, scale_start_index, sample_location, weights,
        batch_size, num_cams, num_feat, num_embeds, num_scale, num_anchors, num_pts, num_groups
    );
}


void deformable_aggregation_grad(
  const float* mc_ms_feat,
  const int* spatial_shape,
  const int* scale_start_index,
  const float* sample_location,
  const float* weights,
  const float* grad_output,
  float* grad_mc_ms_feat,
  float* grad_sampling_location,
  float* grad_weights,
  int batch_size,
  int num_cams,
  int num_feat,
  int num_embeds,
  int num_scale,
  int num_anchors,
  int num_pts,
  int num_groups
) {
    const int num_kernels = batch_size * num_pts * num_embeds * num_anchors * num_cams * num_scale;
    deformable_aggregation_grad_kernel
        <<<(int)ceil(((double)num_kernels/128)), 128>>>(
        num_kernels,
        mc_ms_feat, spatial_shape, scale_start_index, sample_location, weights,
        grad_output, grad_mc_ms_feat, grad_sampling_location, grad_weights,
        batch_size, num_cams, num_feat, num_embeds, num_scale, num_anchors, num_pts, num_groups
    );
}

'''

# ---------------------- pure-PyTorch implementation under test ----------------
# Copied verbatim from diffusiondrive_planner/dfa_torch.py

def deformable_aggregation_torch(
    mc_ms_feat: torch.Tensor,      # (B, num_feat, C) column-major multi-cam multi-scale
    spatial_shape: torch.Tensor,   # (num_cams, num_scale, 2) as [H, W]
    scale_start_index: torch.Tensor,  # (num_cams, num_scale) offsets into num_feat
    sampling_location: torch.Tensor,  # (B, num_anchors, num_pts, num_cams, 2) as [w, h]
    weights: torch.Tensor,         # (B, num_anchors, num_pts, num_cams, num_scale, num_groups)
) -> torch.Tensor:
    """Returns (B, num_anchors, C). Differentiable w.r.t. feat, location and weights."""
    bs, _, num_embeds = mc_ms_feat.shape
    num_cams, num_scale = spatial_shape.shape[:2]
    num_anchors, num_pts = sampling_location.shape[1:3]
    num_groups = weights.shape[-1]

    if num_embeds % num_groups:
        raise ValueError(f"num_embeds {num_embeds} not divisible by num_groups {num_groups}")
    group_size = num_embeds // num_groups

    shapes = spatial_shape.long().tolist()
    starts = scale_start_index.long().tolist()

    # Validity is a property of the location alone, so it is computed once and reused
    # across scales — matching the kernel, where the early return precedes any scale
    # dependent work. Strict inequality on both ends is intentional.
    loc_w = sampling_location[..., 0]
    loc_h = sampling_location[..., 1]
    valid = (loc_w > 0) & (loc_w < 1) & (loc_h > 0) & (loc_h < 1)  # (B, A, P, cams)

    # grid_sample wants [-1, 1] with align_corners=False; see docstring point 3.
    grid = sampling_location * 2.0 - 1.0

    out = mc_ms_feat.new_zeros(bs, num_anchors, num_embeds)

    for cam in range(num_cams):
        cam_valid = valid[..., cam]                       # (B, A, P)
        if not bool(cam_valid.any()):
            continue
        # Zero the grid where invalid so a NaN/inf location cannot leak through
        # grid_sample; the mask below is what actually removes the contribution.
        # zeros_like rather than a scalar/1-element tensor: torch 1.12 (the version in
        # the uniad2.0 env) requires matching rank in torch.where.
        cam_grid_raw = grid[:, :, :, cam, :]
        cam_grid = torch.where(
            cam_valid.unsqueeze(-1), cam_grid_raw, torch.zeros_like(cam_grid_raw)
        )                                                  # (B, A, P, 2)

        for s in range(num_scale):
            h, w = shapes[cam][s]
            start = starts[cam][s]
            # (B, H*W, C) -> (B, C, H, W)
            feat = mc_ms_feat[:, start : start + h * w, :]
            feat = feat.reshape(bs, h, w, num_embeds).permute(0, 3, 1, 2)

            sampled = F.grid_sample(
                feat,
                cam_grid,
                mode="bilinear",
                padding_mode="zeros",
                align_corners=False,
            )                                              # (B, C, A, P)
            sampled = sampled.permute(0, 2, 3, 1)          # (B, A, P, C)

            w_cs = weights[:, :, :, cam, s, :]             # (B, A, P, G)
            w_cs = w_cs.repeat_interleave(group_size, dim=-1)  # contiguous groups
            out = out + (sampled * w_cs * cam_valid.unsqueeze(-1)).sum(dim=2)

    return out


# --------------------------------------------------------------- build the kernel

def build_extension():
    from torch.utils.cpp_extension import load

    tmp = tempfile.mkdtemp(prefix="dfa_")
    (open(os.path.join(tmp, "deformable_aggregation.cpp"), "w")
     .write(CPP_SOURCE))
    (open(os.path.join(tmp, "deformable_aggregation_cuda.cu"), "w")
     .write(CU_SOURCE))

    print("compiling deformable_aggregation_ext (about a minute)...")
    return load(
        name="deformable_aggregation_ext",
        sources=[
            os.path.join(tmp, "deformable_aggregation.cpp"),
            os.path.join(tmp, "deformable_aggregation_cuda.cu"),
        ],
        extra_cuda_cflags=["-O3"],
        verbose=False,
    )


# ------------------------------------------------------------------- test inputs

SHAPES = [[(6, 8), (3, 4), (2, 2)], [(5, 7), (3, 3), (2, 3)]]  # per cam, per level
B, A, P, C, G = 2, 3, 4, 8, 2


def build_inputs(seed, dtype=torch.float32, big=False):
    """Random inputs, with border/outside sampling locations mixed in."""
    if big:
        shapes = [[(32, 88), (16, 44), (8, 22), (4, 11)] for _ in range(6)]
        b, a, p, c, g = 1, 900, 13, 256, 8
    else:
        shapes, b, a, p, c, g = SHAPES, B, A, P, C, G

    gen = torch.Generator().manual_seed(seed)
    sizes = [h * w for cam in shapes for (h, w) in cam]
    feat = torch.randn(b, sum(sizes), c, generator=gen, dtype=dtype)
    spatial_shape = torch.tensor(shapes, dtype=torch.int64)
    starts = (torch.tensor(sizes, dtype=torch.int64).cumsum(0)
              - torch.tensor(sizes, dtype=torch.int64))
    scale_start_index = starts.reshape(len(shapes), -1)

    loc = torch.rand(b, a, p, len(shapes), 2, generator=gen, dtype=dtype)
    if not big:
        # Exercise the kernel's strict early-return.
        loc[0, 0, 0, 0] = torch.tensor([0.0, 0.5], dtype=dtype)
        loc[0, 0, 1, 0] = torch.tensor([1.0, 0.5], dtype=dtype)
        loc[0, 1, 0, 0] = torch.tensor([-0.3, 0.5], dtype=dtype)
        loc[0, 1, 1, 0] = torch.tensor([0.5, 1.7], dtype=dtype)

    weights = torch.randn(b, a, p, len(shapes), len(shapes[0]), g,
                          generator=gen, dtype=dtype)
    return [x.cuda() for x in
            (feat, spatial_shape, scale_start_index, loc, weights)]


# ------------------------------------------------------------------ diagnostics

def diagnose(name, got, want, err, denom):
    """Explain any large RELATIVE error.

    A big relative error with a tiny absolute error is the expected signature of
    float32 accumulation-order differences: the CUDA kernel sums via atomicAdd in
    nondeterministic order across cam x scale x pts, while the torch version sums in a
    fixed loop order. That shows up as a large ratio only where the true value is near
    zero, which is harmless.

    The failure mode it must be distinguished from is a genuine structural mismatch,
    which would produce large relative error on LARGE values too. So report the relative
    error restricted to elements that actually carry magnitude.
    """
    rel = err / denom
    i = int(rel.argmax())
    flat_want, flat_err = want.flatten(), err.flatten()

    scale = float(want.abs().median())
    big = want.abs() > max(scale, 1e-3)          # elements that carry real magnitude
    rel_big = float((rel[big]).max()) if bool(big.any()) else float("nan")
    frac_bad = float((rel > 1e-2).float().mean())

    print(f"{'':<28}worst-rel elem: |want|={abs(float(flat_want[i])):.3e} "
          f"err={float(flat_err[i]):.3e}")
    print(f"{'':<28}median |want|={scale:.3e} | max rel on |want|>median: {rel_big:.3e} "
          f"| frac rel>1%: {frac_bad:.2%}")
    if rel_big > 1e-3:
        print(f"{'':<28}^^ WARNING: large relative error on LARGE values — "
              f"this is NOT just accumulation order.")


# ------------------------------------------------------------------------ main

def main():
    ext = build_extension()

    print()
    print("=" * 66)
    print(f"{'case':<28}{'max abs diff':>16}{'max rel diff':>14}  verdict")
    print("=" * 66)

    worst = 0.0
    failures = 0
    cases = [("tiny seed=0", 0, False), ("tiny seed=1", 1, False),
             ("tiny seed=2", 2, False), ("realistic 900x13x256", 0, True)]

    for name, seed, big in cases:
        args = build_inputs(seed, big=big)
        feat, spatial_shape, scale_start_index, loc, weights = args

        want = ext.deformable_aggregation_forward(
            feat.contiguous().float(),
            spatial_shape.contiguous().int(),
            scale_start_index.contiguous().int(),
            loc.contiguous().float(),
            weights.contiguous().float(),
        )
        got = deformable_aggregation_torch(*args)

        denom = want.abs().clamp(min=1e-6)
        err = (got - want).abs()
        abs_d = float(err.max())
        rel_d = float((err / denom).max())
        ok = abs_d < 1e-3
        failures += (not ok)
        worst = max(worst, abs_d)
        print(f"{name:<28}{abs_d:>16.3e}{rel_d:>14.3e}  {'PASS' if ok else 'FAIL'}")
        diagnose(name, got, want, err, denom)

    print("=" * 66)
    if failures:
        print(f"\n{failures} case(s) FAILED — dfa_torch.py does NOT match the kernel.")
        print("Do not trust any metric produced with the pure-PyTorch fallback.")
    else:
        print(f"\nAll cases PASS (worst abs diff {worst:.3e}).")
        print("dfa_torch.py is confirmed equivalent to the CUDA kernel.")
    return failures


def _in_notebook() -> bool:
    try:
        get_ipython()  # noqa: F821  — only defined inside IPython/Jupyter
        return True
    except NameError:
        return False


# Works both as `python validate_dfa_cuda.py` and as a pasted notebook cell.
# SystemExit inside a Jupyter cell renders as an ugly traceback, so it is only
# raised when actually running as a script.
_rc = main()
if _rc and not _in_notebook():
    raise SystemExit(_rc)
